apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql
  namespace: rdbms
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-app # this helps service find the deployment
    spec:
      containers:
        - name: mysql-container
          image: wangxian/alpine-mysql
          ports:
            - containerPort: 3306
              name: mysql-port
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root_password

