# First encode credentials as base64 string
# echo -n 'Nur Rony' | base64 | pbcopy
# echo -n 'This is super secret' | base64 | pbcopy
apiVersion: v1
kind: Secret
metadata:
  name: demo-secrets
  namespace: experiments
data:
  username: TnVyIFJvbnk=
  password: VGhpcyBpcyBzdXBlciBzZWNyZXQ=

---
kind: Pod
apiVersion: v1
metadata:
  name: distribute-cred-through-secret
  labels:
    name: distribute-cred-through-secret
spec:
  restartPolicy: Never
  volumes:
    - name: secret-volume
      secret:
        secretName: demo-secrets
  containers:
    - name: distribute-cred-through-secret
      image: k8s.gcr.io/busybox
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /etc/app-secret
          name: secret-volume
      command:
        - cat
        - /etc/app-secret/username
        - /etc/app-secret/password
      resources:
        limits:
          cpu: 100m
          memory: 32Mi
