##
# It is good to encrypt secret data in base64 like below
# echo -n 'nurrony' | base64
# echo -n 'super-secret-pass' | base64
##

apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  username: bnVycm9ueQ==
  password: c3VwZXItc2VjcmV0LXBhc3N3b3Jk
