kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  volumes:
    - name: my-vol
      hostPath:
        path: /Users/nurrony/Documents/

  containers:
    - name: nginx-container
      image: nginx:alpine
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: my-vol