apiVersion: v1
kind: LimitRange
metadata:
  name: memory-cpu-limit-range
  namespace: experiments
spec:
  limits:
    - default:
        cpu: 1
        memory: 1Gi
      defaultRequest:
        cpu: '0.5'
        memory: 512Mi # must be equal or grater than min memory
      max:
        memory: 1Gi
      min:
        memory: 256Mi
      type: Container
