apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose-gitlab.yaml
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis
    spec:
      containers:
      - args:
        - --loglevel warning
        image: sameersbn/redis:latest
        name: redis
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/redis
          name: gitlab-radis-volume
      restartPolicy: Always
      volumes:
      - name: gitlab-radis-volume
        persistentVolumeClaim:
          claimName: gitlab-radis-volume
status: {}
