apiVersion: v1
kind: Pod
metadata:
  name: secret-env-test-pod
spec:
  containers:
    - name: secret-env-test-container
      image: nginx:alpine
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: password